import { useEffect, useRef, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api, ApiError } from '@/services/api-client'
import type { PlaceSummary } from '@/types'
import { approvedSpeciesDataset } from '@shared/catalogue'
import { eventsApi, type EventDraft, type EventType } from '@/services/api/events'
import { EventMap } from './EventMap'
import { State } from './EventsDiscoveryPage'
import { eventTypeLabels } from './event-types'

const initial: EventDraft = { title: '', purpose: '', eventType: 'survey', placeId: '', meetingLatitude: 3.139, meetingLongitude: 101.687, startAt: '', endAt: '', targetSpeciesIds: [], permissionContext: 'unknown' }
type FormErrors = Partial<Record<keyof EventDraft | 'times', string>>

export function HostEventPage() {
  const { eventId } = useParams(); const edit = Boolean(eventId); const navigate = useNavigate()
  const [draft, setDraft] = useState<EventDraft>(initial); const [step, setStep] = useState(1); const [errors, setErrors] = useState<FormErrors>({}); const [createdId, setCreatedId] = useState<string | null>(null)
  const initialized = useRef<string | null>(null)
  const places = useQuery({ queryKey: ['places'], queryFn: () => api<{ items: PlaceSummary[] }>('/api/v1/places') })
  const existing = useQuery({ queryKey: ['event', eventId], queryFn: () => eventsApi.get(eventId!), enabled: edit })
  useEffect(() => { const item = existing.data; if (!item || initialized.current === eventId) return; initialized.current = eventId ?? null; setDraft({ title: item.title, purpose: item.purpose, eventType: item.eventType, placeId: item.placeId, meetingLatitude: item.meetingLatitude, meetingLongitude: item.meetingLongitude, meetingNote: item.meetingNote ?? '', startAt: localInput(item.startAt), endAt: localInput(item.endAt), targetSpeciesIds: item.targetSpeciesIds, safetyNotes: item.safetyNotes ?? '', permissionContext: item.permissionContext, chatLink: item.chatLink ?? '' }) }, [eventId, existing.data])
  const save = useMutation({ mutationFn: async (publish: boolean) => { const wire = { ...draft, startAt: new Date(draft.startAt).toISOString(), endAt: new Date(draft.endAt).toISOString() }; if (edit) { const patch: Partial<EventDraft> = existing.data?.status === 'draft' && publish ? { ...wire, status: 'published' } : wire; if (existing.data?.activityLocked) { delete patch.placeId; delete patch.meetingLatitude; delete patch.meetingLongitude; delete patch.startAt; delete patch.endAt; delete patch.eventType } return eventsApi.update(eventId!, patch) } if (createdId) return eventsApi.update(createdId, { ...wire, ...(publish ? { status: 'published' as const } : {}) }); const created = await eventsApi.create(wire); setCreatedId(created.eventId); return publish ? eventsApi.update(created.eventId, { status: 'published' }) : created }, onSuccess: value => navigate(`/events/${'eventId' in value ? value.eventId : value.id}`) })
  const set = <K extends keyof EventDraft>(key: K, value: EventDraft[K]) => { setDraft(previous => ({ ...previous, [key]: value })); setErrors(previous => ({ ...previous, [key]: undefined, ...(key === 'startAt' || key === 'endAt' ? { times: undefined } : {}) })) }
  const validate = (at: number) => { const next: FormErrors = {}; if (at >= 1) { if (!draft.title.trim()) next.title = 'Enter an event title.'; if (!draft.purpose.trim()) next.purpose = 'Describe the event purpose.' } if (at >= 2) { if (!draft.placeId) next.placeId = 'Choose a mapped place.'; if (!Number.isFinite(draft.meetingLatitude) || draft.meetingLatitude < .8 || draft.meetingLatitude > 7.5) next.meetingLatitude = 'Enter a meeting latitude in Malaysia.'; if (!Number.isFinite(draft.meetingLongitude) || draft.meetingLongitude < 99.3 || draft.meetingLongitude > 119.5) next.meetingLongitude = 'Enter a meeting longitude in Malaysia.' } if (at >= 3) { if (!draft.startAt || !draft.endAt || new Date(draft.endAt) <= new Date(draft.startAt)) next.times = 'Enter a valid end time after the start time.'; if (draft.eventType === 'removal' && draft.permissionContext !== 'explicit_permission') next.permissionContext = 'Removal events require explicit permission.' } if (at >= 4 && draft.chatLink?.trim() && !validChatLink(draft.chatLink)) next.chatLink = 'Enter a valid HTTPS chat link without account credentials.'; setErrors(next); return !Object.keys(next).length }
  if (edit && existing.isLoading) return <State text="Loading event editor…" />
  if (edit && (existing.isError || !existing.data)) return <State error text="This event cannot be edited." />
  if (edit && !existing.data!.isHost) return <State error text="Only the event host can edit this event." />
  const locked = existing.data?.activityLocked
  const next = () => { if (validate(step)) setStep(step + 1) }
  const submit = (publish: boolean) => { if (validate(4)) save.mutate(publish) }
  return <section className="events-page host-event"><Link className="back-link" to={edit ? `/events/${eventId}` : '/events'}>Back to events</Link><h1>{edit ? 'Edit event' : 'Host a community event'}</h1>{locked && <p className="event-notice" role="status">Attendance or reports have started. Place, meeting point, times and event type are locked.</p>}<p>Step {step} of 4</p>
    {step === 1 && <fieldset><legend>What is this event?</legend><label>Title<input value={draft.title} maxLength={120} onChange={e => set('title', e.target.value)} aria-invalid={Boolean(errors.title)} />{errors.title && <small role="alert">{errors.title}</small>}</label><label>Purpose<textarea value={draft.purpose} onChange={e => set('purpose', e.target.value)} aria-invalid={Boolean(errors.purpose)} />{errors.purpose && <small role="alert">{errors.purpose}</small>}</label><label>Activity type<select value={draft.eventType} disabled={locked} onChange={e => set('eventType', e.target.value as EventType)}>{Object.entries(eventTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></fieldset>}
    {step === 2 && <fieldset><legend>Choose the place and meeting point</legend>{places.isLoading && <p role="status">Loading mapped places…</p>}{places.isError && <p role="alert">Mapped places could not be loaded. <button onClick={() => void places.refetch()}>Try again</button></p>}<label>Mapped place<select value={draft.placeId} disabled={locked || places.isLoading} onChange={e => set('placeId', e.target.value)} aria-invalid={Boolean(errors.placeId)}><option value="">Choose a mapped place</option>{places.data?.items.map(place => <option key={place.placeId} value={place.placeId}>{place.displayName}</option>)}</select>{errors.placeId && <small role="alert">{errors.placeId}</small>}</label><EventMap point={{ latitude: draft.meetingLatitude, longitude: draft.meetingLongitude }} onPointChange={locked ? undefined : point => { set('meetingLatitude', point.latitude); set('meetingLongitude', point.longitude) }} label="Select a meeting point on the map" /><div className="event-coordinate"><label>Meeting latitude<input type="number" step=".00001" disabled={locked} value={draft.meetingLatitude} onChange={e => set('meetingLatitude', Number(e.target.value))} />{errors.meetingLatitude && <small role="alert">{errors.meetingLatitude}</small>}</label><label>Meeting longitude<input type="number" step=".00001" disabled={locked} value={draft.meetingLongitude} onChange={e => set('meetingLongitude', Number(e.target.value))} />{errors.meetingLongitude && <small role="alert">{errors.meetingLongitude}</small>}</label></div><label>Meeting note<input maxLength={500} value={draft.meetingNote ?? ''} onChange={e => set('meetingNote', e.target.value)} /></label></fieldset>}
    {step === 3 && <fieldset><legend>Set the time and safety context</legend><label>Starts<input type="datetime-local" disabled={locked} value={draft.startAt} onChange={e => set('startAt', e.target.value)} /></label><label>Ends<input type="datetime-local" disabled={locked} value={draft.endAt} onChange={e => set('endAt', e.target.value)} /></label>{errors.times && <p role="alert">{errors.times}</p>}<label>Permission context<select value={draft.permissionContext} onChange={e => set('permissionContext', e.target.value as EventDraft['permissionContext'])}><option value="unknown">Permission not confirmed</option><option value="explicit_permission">Explicit permission confirmed</option></select></label>{errors.permissionContext && <p role="alert">{errors.permissionContext}</p>}<label>Safety notes<textarea value={draft.safetyNotes ?? ''} onChange={e => set('safetyNotes', e.target.value)} /></label></fieldset>}
    {step === 4 && <fieldset><legend>Finish the event details</legend><label>Target species<select multiple value={draft.targetSpeciesIds} onChange={e => set('targetSpeciesIds', Array.from(e.currentTarget.selectedOptions, option => option.value))}>{approvedSpeciesDataset.records.map(item => <option key={item.species_id} value={item.species_id}>{item.common_names[0] ?? item.scientific_name}</option>)}</select></label><label>Event chat link (optional)<input type="url" maxLength={500} value={draft.chatLink ?? ''} onChange={e => set('chatLink', e.target.value)} placeholder="https://…" aria-invalid={Boolean(errors.chatLink)} />{errors.chatLink && <small role="alert">{errors.chatLink}</small>}</label><p className="event-notice">Joining does not grant removal permission. State safety and permission information clearly for participants.</p></fieldset>}
    <div className="event-actions">{step > 1 && <button onClick={() => setStep(step - 1)}>Back</button>}{step < 4 ? <button className="event-primary" onClick={next}>Continue</button> : edit && existing.data?.status !== 'draft' ? <button className="event-primary" disabled={save.isPending} onClick={() => submit(false)}>Save changes</button> : <><button disabled={save.isPending} onClick={() => submit(false)}>Save draft</button><button className="event-primary" disabled={save.isPending} onClick={() => submit(true)}>Publish event</button></>}</div>{save.error && <p role="alert">{save.error instanceof ApiError ? save.error.message : 'The event could not be saved. Try again.'}</p>}</section>
}
const localInput = (value: string) => { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16) }

function validChatLink(value: string) { try { const url = new URL(value); return value.length <= 500 && url.protocol === 'https:' && Boolean(url.hostname) && !url.username && !url.password } catch { return false } }
