"""Remove exact development-only place anchors from production reference data.

Revision ID: 20260914_17
Revises: 20260913_16
"""

from __future__ import annotations

import uuid

import sqlalchemy as sa

from alembic import op

revision = "20260914_17"
down_revision = "20260913_16"
branch_labels = None
depends_on = None

DEVELOPMENT_PLACE_NAMES = (
    "Bukit Kiara · West Trail",
    "Bukit Kiara · Look-out",
    "Bukit Kiara · Picnic Area",
    "Bukit Kiara · Ridge Path",
    "Taman Tugu · Pond edge",
    "Bukit Nanas · Reserve entrance",
    "FRIM Kepong · Canopy walk",
    "KLCC Park · East pond",
    "Kota Damansara Community Forest",
    "Bukit Gasing · North gate",
)
DEVELOPMENT_SIGHTING_IDS = tuple(
    uuid.uuid5(uuid.NAMESPACE_URL, f"invatrace-seed-sighting-{index}")
    for index in range(1, 11)
)


def upgrade() -> None:
    sightings = sa.table("sightings", sa.column("id", sa.Uuid()))
    links = sa.table(
        "report_sighting_links",
        sa.column("sighting_id", sa.Uuid()),
    )
    monitored_places = sa.table("monitored_places", sa.column("name", sa.String()))

    # Delete only the deterministic demo sightings, and never touch one that a
    # real report was linked to. The exact IDs are generated by seed.py.
    op.execute(
        sightings.delete()
        .where(sightings.c.id.in_(DEVELOPMENT_SIGHTING_IDS))
        .where(
            ~sa.exists(
                sa.select(1).where(links.c.sighting_id == sightings.c.id)
            )
        )
    )
    # These exact anchors were inserted by the old production reference loader.
    # Reports retain their already stored place labels.
    op.execute(monitored_places.delete().where(monitored_places.c.name.in_(DEVELOPMENT_PLACE_NAMES)))


def downgrade() -> None:
    # A downgrade must not recreate demonstration geography in production.
    pass
